const FIREBASE_API_KEY = "FIREBASE_API_KEY";
const FIREBASE_AUTH_DOMAIN = "FIREBASE_AUTH_DOMAIN";
const FIREBASE_DATABASE_URL = "FIREBASE_DATABASE_URL";
const FIREBASE_PROJECT_ID = "FIREBASE_PROJECT_ID";
const FIREBASE_STORAGE_BUCKET = "FIREBASE_STORAGE_BUCKET";
const FIREBASE_MESSAGING_SENDER_ID = "FIREBASE_MESSAGING_SENDER_ID";

export const FIREBASE_CONFIG = {
  apiKey: FIREBASE_API_KEY,
  authDomain: FIREBASE_AUTH_DOMAIN,
  databaseURL: FIREBASE_DATABASE_URL,
  projectId: FIREBASE_PROJECT_ID,
  storageBucket: FIREBASE_STORAGE_BUCKET,
  messagingSenderId: FIREBASE_MESSAGING_SENDER_ID,
};

export const COLLECTION_STORIES = 'stories';
